from ABC.pages import header


def about():
    header()
    about = """ 
About :

Founded in 1867, A. B. C INSTITUTE OF TECHNOLOGY is a private, research university comprised of 13 schools and colleges. Students pursue studies in more than 120 areas leading to undergraduate, graduate and professional degrees. To date, A. B. C  has awarded more than 120,000 degrees in the arts, the sciences, and the humanities. The historic main campus sits on a hilltop in Northwest Washington blocks from the storied U Street and A. B. C  Theatre. We are two miles from the U.S. Capitol where many students intern, and scores of alumni shape national and foreign policy.A. B. C  is a leader in STEM fields. The National Science Foundation has ranked A. B. C  as the top producer of African-American undergraduates who later earn science and engineering doctoral degrees. The University also boasts nationally ranked programs in social work, business and communication sciences and disorders. In 2013, The Washington Post named A. B. C  "An Incubator for Cinematographers."

       The College of Engineering is internationally regarded for its illustrious legacy of training students to become competent and compassionate physicians who provide knowledge in technical underserved communities at home and abroad. The College is a national leader in studying technical disparities among people of color and is one of America's top institutions for training women surgeons. The A. B. C INSTITUTE OF TECHNOLOGY technical Sciences division includes the A. B. C INSTITUTE OF TECHNOLOGY Hospital and the Colleges of Dentistry, Pharmacy, and as well as Nursing and Allied technical Sciences.For more than 140 years, the A. B. C INSTITUTE OF TECHNOLOGY School of Law has served as an advocate for social justice and as an architect of social change. It has produced more than 4,000 social engineers including the first African-American Supreme Court Justice, noted legislators, civil rights attorneys, mayors and public officials across the United States. In 2012, the Law School was ranked among the top 20 public service schools by National Jurist magazine.The University's motto Veritas et Utilitas, Truth and Service, represents a key part of our identity. The more than 10,000 undergraduate and graduate students dedicate hundreds of hours each year to service in nearby LeDroit Park, around the nation and far-flung places around the world. Over the U.S. Peace Corps' 50-year history, more than 200 A. B. C  graduates have served as volunteers around the globe, the highest number among historically-Black colleges. In 2012, a A. B. C  senior who led Engineers Without Borders service projects in Kenya and Brazil was named a White House "Champion of Change."The University remains committed to further enhancing its strategic positioning as one of the top research universities in the nation. As we approach our sesquicentennial in 2017, we are uniquely positioned to have the next 150 years as glorious as the past.

Vision : 

To achieve excellence in professional education and create an ecosystem for the holistic development of all stakeholders

Mission :

The mission of A. B. C INSTITUTE OF TECHNOLOGY  is to advance knowledge and educate students in science, technology, and other areas of scholarship that will best serve the nation and the world in the 21st century.The Institute is committed to generating, disseminating, and preserving knowledge, and to working with others to bring this knowledge to bear on the world’s great challenges. A. B. C INSTITUTE OF TECHNOLOGY  is dedicated to providing its students with an education that combines rigorous academic study and the excitement of discovery with the support and intellectual stimulation of a diverse campus community. We seek to develop in each member of the A. B. C INSTITUTE OF TECHNOLOGY  community the ability and passion to work wisely, creatively, and effectively for the betterment of humankind. """
    print(about)
